CREATE TABLE invoice (
    id UUID NOT NULL,
    order_id VARCHAR(255),
    customer_id UUID NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE,
    paid_at TIMESTAMP WITH TIME ZONE,
    canceled_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    total_amount DECIMAL(19,2),
    status VARCHAR(255) NOT NULL,
    payment_settings_id UUID,
    payer_full_name VARCHAR(255),
    payer_document VARCHAR(255),
    payer_phone VARCHAR(255),
    payer_email VARCHAR(255),
    payer_address_street VARCHAR(255),
    payer_address_number VARCHAR(255),
    payer_address_complement VARCHAR(255),
    payer_address_neighborhood VARCHAR(255),
    payer_address_city VARCHAR(255),
    payer_address_state VARCHAR(255),
    payer_address_zip_code VARCHAR(255),
    cancel_reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    created_by_user_id UUID,
    last_modified_date TIMESTAMP WITH TIME ZONE,
    last_modified_by_user_id UUID,
    version INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (payment_settings_id) REFERENCES payment_settings (id)
);

